import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Plus } from "lucide-react";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-serif`}
      >
        <div className="relative">
          <button className="fixed top-8 right-8 w-12 h-12 bg-black rounded-full flex items-center justify-center hover:scale-110 transition-transform z-10">
            <Plus className="w-6 h-6 text-white" />
          </button>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
